//! Multi-chip STARK prover.
//!
//! Uses `p3-uni-stark::prove()` per chip for main constraint proofs,
//! then records LogUp interactions and computes cross-chip cumulative sums.
//!
//! Generic over `CS: StarkAir` — callers specify their chip set at the call site:
//! ```ignore
//! let proof = prove::<TabulaAir>(&default_config(), &traces);
//! ```

use p3_air::Air;
use p3_baby_bear::BabyBear;
use p3_field::PrimeCharacteristicRing;
use p3_matrix::Matrix;
use p3_matrix::dense::RowMajorMatrix;
use p3_uni_stark::{self, setup_preprocessed};

use crate::air::chip_instance::ChipInstance;
use crate::air::chip_set::ChipSet;
use crate::debug::evaluate_chip_with_preprocessed_and_public_values;
use crate::trace::TraceMap;

use super::config::{EF4, TabulaStarkConfig, default_config};
use super::permutation;
use super::proof::{ChipProofEntry, TabulaProof};

/// Trait alias for the full set of Air bounds required by the STARK prover/verifier.
///
/// The p3-uni-stark pipeline calls `eval()` with four different builder types:
/// - `SymbolicAirBuilder` (constraint degree inference)
/// - `ProverConstraintFolder` (prover constraint accumulation)
/// - `DebugConstraintBuilder` (p3's internal debug checking)
/// - `VerifierConstraintFolder` (verifier constraint checking)
///
/// Plus our own `debug::DebugConstraintBuilder` for LogUp interaction recording.
///
/// All implement `InteractionAirBuilder + AirBuilderWithPublicValues` via bridge impls,
/// so any chip set generated by `define_chip_set!` automatically satisfies this.
pub trait StarkAir:
    ChipSet
    + Air<p3_uni_stark::SymbolicAirBuilder<BabyBear>>
    + for<'a> Air<p3_uni_stark::ProverConstraintFolder<'a, TabulaStarkConfig>>
    + for<'a> Air<p3_uni_stark::DebugConstraintBuilder<'a, BabyBear>>
    + for<'a> Air<p3_uni_stark::VerifierConstraintFolder<'a, TabulaStarkConfig>>
    + for<'a> Air<crate::debug::DebugConstraintBuilder<'a, BabyBear>>
{
}

impl<T> StarkAir for T where
    T: ChipSet
        + Air<p3_uni_stark::SymbolicAirBuilder<BabyBear>>
        + for<'a> Air<p3_uni_stark::ProverConstraintFolder<'a, TabulaStarkConfig>>
        + for<'a> Air<p3_uni_stark::DebugConstraintBuilder<'a, BabyBear>>
        + for<'a> Air<p3_uni_stark::VerifierConstraintFolder<'a, TabulaStarkConfig>>
        + for<'a> Air<crate::debug::DebugConstraintBuilder<'a, BabyBear>>
{
}

/// Generate a Tabula STARK proof from a [`TraceMap`].
///
/// Iterates `CS::all_chips()`, looks up each chip's trace in the map,
/// and runs per-chip STARK proofs + cross-chip LogUp balance check.
///
/// # Panics
///
/// Panics if any chip's trace height is not a power of two (p3 requirement).
pub fn prove<CS: StarkAir>(config: &TabulaStarkConfig, traces: &TraceMap) -> TabulaProof {
    let instances = build_chip_instances::<CS>(traces);
    let mut chip_proofs = Vec::with_capacity(instances.len());

    // Collect main traces for LogUp check. Each entry is (instance_index, main_trace, pvs).
    let mut active_chips: Vec<(usize, RowMajorMatrix<BabyBear>, Vec<BabyBear>)> = Vec::new();

    // ── Phase 1: Per-chip STARK proofs ──────────────────────────────────────
    for (idx, instance) in instances.iter().enumerate() {
        let chip_name = instance.name();
        let entry = traces.get(chip_name).expect("chip trace must exist");
        let main_trace = &entry.main;
        let height = main_trace.height();

        // Skip empty chips (height 0 — no rows to prove).
        if height == 0 {
            continue;
        }

        // p3-uni-stark requires power-of-two trace heights.
        assert!(
            height.is_power_of_two(),
            "chip '{chip_name}' trace height {height} is not a power of two"
        );

        let degree_bits = height.trailing_zeros() as usize;
        let pp_setup = setup_preprocessed(config, instance, degree_bits);
        let (pp_prover, pp_vk) = match pp_setup {
            Some((prover, vk)) => (Some(prover), Some(vk)),
            None => (None, None),
        };
        let proof = p3_uni_stark::prove_with_preprocessed(
            config,
            instance,
            main_trace.clone(),
            &entry.public_values,
            pp_prover.as_ref(),
        );

        chip_proofs.push(ChipProofEntry {
            chip_name,
            proof,
            cumsum_final: EF4::ZERO,
            trace_height: height,
            public_values: entry.public_values.clone(),
            preprocessed_vk: pp_vk,
        });

        active_chips.push((idx, main_trace.clone(), entry.public_values.clone()));
    }

    // ── Phase 2: Fiat-Shamir challenge derivation ───────────────────────────
    let challenges = permutation::derive_challenges(&chip_proofs);

    // ── Phase 3: LogUp cross-chip balance check (EF4 fingerprints) ────────
    let records = compute_chip_records(&instances, &active_chips, traces);
    let cumsums = permutation::compute_cumsums_ef4(&records, challenges);

    assert_eq!(
        chip_proofs.len(),
        cumsums.len(),
        "chip_proofs and cumsums must have the same length"
    );

    let mut cumsum_total = EF4::ZERO;
    for (entry, cumsum) in chip_proofs.iter_mut().zip(cumsums.iter()) {
        entry.cumsum_final = *cumsum;
        cumsum_total += *cumsum;
    }

    assert_eq!(
        cumsum_total,
        EF4::ZERO,
        "LogUp balance check failed during proving: cumsum total is nonzero"
    );

    TabulaProof {
        chip_proofs,
        logup_challenges: challenges,
    }
}

/// Generate a STARK proof using the default configuration.
pub fn prove_default<CS: StarkAir>(traces: &TraceMap) -> TabulaProof {
    prove::<CS>(&default_config(), traces)
}

/// Build chip instances from a `TraceMap` using `CS::all_chips()`.
fn build_chip_instances<CS: ChipSet>(traces: &TraceMap) -> Vec<ChipInstance<CS>> {
    ChipInstance::build_all(traces)
}

/// Record interactions from all chips for LogUp balance checking.
fn compute_chip_records<CS: StarkAir>(
    instances: &[ChipInstance<CS>],
    active_chips: &[(usize, RowMajorMatrix<BabyBear>, Vec<BabyBear>)],
    traces: &TraceMap,
) -> Vec<crate::debug::ChipRecord<BabyBear>> {
    let mut records = Vec::new();
    for &(idx, ref main_trace, ref pvs) in active_chips {
        let instance = &instances[idx];
        let entry = traces.get(instance.name()).expect("chip trace must exist");
        let record = evaluate_chip_with_preprocessed_and_public_values(
            instance.name(),
            instance.air(),
            main_trace,
            entry.preprocessed.as_ref(),
            pvs,
        )
        .expect("constraint check should pass during proving");
        records.push(record);
    }
    records
}
