[package]
name = "tabula-ext"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["prove"]
verify = [
    "dep:tabula-machine",
    "dep:tabula-stark",
    "dep:tabula-chips",
    "dep:tabula-commitment",
    "dep:p3-air",
    "dep:p3-field",
    "dep:p3-koala-bear",
    "dep:p3-matrix",
]
prove = [
    "verify",
    "dep:tabula-executor",
    "dep:tabula-gadgets",
    "dep:tabula-witness",
]

[dependencies]
thiserror = { workspace = true }
tabula-artifact = { workspace = true }
tabula-contract = { workspace = true }
tabula-core = { workspace = true }
tabula-types = { workspace = true }
tabula-ir = { workspace = true }
tabula-profile = { workspace = true }
tabula-chips = { workspace = true, optional = true }
tabula-machine = { workspace = true, optional = true }
tabula-stark = { workspace = true, optional = true }
tabula-executor = { workspace = true, optional = true }
tabula-commitment = { workspace = true, optional = true, features = ["stark"] }
tabula-gadgets = { workspace = true, optional = true }
tabula-witness = { workspace = true, optional = true }
p3-air = { workspace = true, optional = true }
p3-field = { workspace = true, optional = true }
p3-koala-bear = { workspace = true, optional = true }
p3-matrix = { workspace = true, optional = true }

[lints]
workspace = true
