[package]
name = "tabula-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tabula-core = { workspace = true, features = ["test-utils"] }
tabula-sdk = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
borsh = { workspace = true }

[lints]
workspace = true
