//! AIR chip implementations.
//!
//! Each chip is a small struct implementing `BaseAir` + `Air`.
//! The `TabulaAir` enum dispatches to the appropriate chip via [`define_chip_set!`].
//! All chips also implement [`ChipSpec`] for introspection.

pub mod column_meta;
pub mod execution;
pub mod inter_tx_order;
pub mod poseidon;
pub mod range_check;
pub mod smt_path;
pub mod state_column;
pub mod static_table;

use column_meta::ColumnMetaChip;
use execution::ExecutionChip;
use inter_tx_order::InterTxOrderChip;
use poseidon::PoseidonChip;
use range_check::RangeCheckChip;
use smt_path::{SmtColPathChip, SmtTablePathChip};
use state_column::StateColumnChip;
use static_table::StaticTableChip;

/// Metadata and capability interface for AIR chips.
///
/// Chip name is used by debug checking, error messages, and [`crate::air::chip_set::ChipSet`]
/// for name-based dispatch in the prover/verifier.
///
/// The `Default` bound enables construction from ZSTs in `ChipSet::all_chips()`.
/// `Send + Sync` enables parallel proving across chips.
pub trait ChipSpec: Default + Send + Sync {
    /// Human-readable chip name (e.g. `"ColumnMeta"`).
    fn chip_name(&self) -> &'static str;

    /// Number of public values consumed by this chip (default: 0).
    fn num_public_values(&self) -> usize {
        0
    }

    /// Width of preprocessed trace columns (default: 0 = no preprocessed).
    ///
    /// A nonzero value indicates this chip has a preprocessed trace.
    /// Used by `InteractionExtractor` to construct symbolic variables.
    fn preprocessed_width(&self) -> usize {
        0
    }

    /// Whether this chip declares any LogUp interactions (default: true).
    /// Chips with no interactions skip permutation trace generation.
    fn has_interactions(&self) -> bool {
        true
    }
}

// ── Default + ChipSpec for each chip ────────────────────────────────────────

impl Default for ColumnMetaChip {
    fn default() -> Self {
        Self
    }
}
impl ChipSpec for ColumnMetaChip {
    fn chip_name(&self) -> &'static str {
        "ColumnMeta"
    }
}

impl Default for RangeCheckChip {
    fn default() -> Self {
        Self
    }
}
impl ChipSpec for RangeCheckChip {
    fn chip_name(&self) -> &'static str {
        "RangeCheck"
    }
    fn has_interactions(&self) -> bool {
        false
    }
}

impl Default for PoseidonChip {
    fn default() -> Self {
        Self
    }
}
impl ChipSpec for PoseidonChip {
    fn chip_name(&self) -> &'static str {
        "Poseidon"
    }
    fn preprocessed_width(&self) -> usize {
        poseidon::POSEIDON_PREPROCESSED_WIDTH
    }
}

impl<const W: usize> Default for ExecutionChip<W> {
    fn default() -> Self {
        Self
    }
}
impl<const W: usize> ChipSpec for ExecutionChip<W> {
    fn chip_name(&self) -> &'static str {
        "Execution"
    }
}

impl<const W: usize> Default for StateColumnChip<W> {
    fn default() -> Self {
        Self
    }
}
impl<const W: usize> ChipSpec for StateColumnChip<W> {
    fn chip_name(&self) -> &'static str {
        "StateColumn"
    }
}

impl<const W: usize> Default for InterTxOrderChip<W> {
    fn default() -> Self {
        Self
    }
}
impl<const W: usize> ChipSpec for InterTxOrderChip<W> {
    fn chip_name(&self) -> &'static str {
        "InterTxOrder"
    }
}

impl<const W: usize> Default for StaticTableChip<W> {
    fn default() -> Self {
        Self
    }
}
impl<const W: usize> ChipSpec for StaticTableChip<W> {
    fn chip_name(&self) -> &'static str {
        "StaticTable"
    }
}

impl Default for SmtColPathChip {
    fn default() -> Self {
        Self
    }
}
impl ChipSpec for SmtColPathChip {
    fn chip_name(&self) -> &'static str {
        "SmtColPath"
    }
}

impl Default for SmtTablePathChip {
    fn default() -> Self {
        Self
    }
}
impl ChipSpec for SmtTablePathChip {
    fn chip_name(&self) -> &'static str {
        "SmtTablePath"
    }
    fn num_public_values(&self) -> usize {
        smt_path::air::SMT_TABLE_PATH_NUM_PUBLIC_VALUES
    }
}

// ── TabulaAir: the default chip set ─────────────────────────────────────────

crate::define_chip_set! {
    /// Top-level AIR enum for multi-chip proving.
    ///
    /// Generated by [`define_chip_set!`] — delegates `BaseAir`, `Air`, `ChipSpec`,
    /// and `ChipSet` to the contained chip variant.
    pub enum TabulaAir {
        /// Execution chip with Standard value width (W=3).
        Execution(ExecutionChip<3>),
        /// InterTxOrder chip with Standard value width (W=3).
        InterTxOrder(InterTxOrderChip<3>),
        /// StateColumn chip with Standard value width (W=3).
        StateColumn(StateColumnChip<3>),
        /// ColumnMeta global table.
        ColumnMeta(ColumnMetaChip),
        /// Poseidon2 permutation chip.
        Poseidon(PoseidonChip),
        /// Range check preprocessed table.
        RangeCheck(RangeCheckChip),
        /// StaticTable chip with Standard value width (W=3).
        StaticTable(StaticTableChip<3>),
        /// SmtColPath chip (column-level SMT paths).
        SmtColPath(SmtColPathChip),
        /// SmtTablePath chip (table-level SMT paths).
        SmtTablePath(SmtTablePathChip),
    }
}
