[package]
name = "tabula-web-ide"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
gloo-file = "0.3"
gloo-net = "0.6"
hex = "0.4"
js-sys = "0.3"
leptos = { version = "0.7", features = ["csr"] }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tabula-artifact = { workspace = true }
tabula-core = { workspace = true }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
    "Blob",
    "BlobPropertyBag",
    "Document",
    "Event",
    "File",
    "FileList",
    "FileReader",
    "HtmlAnchorElement",
    "HtmlInputElement",
    "HtmlTextAreaElement",
    "KeyboardEvent",
    "Storage",
    "Url",
    "Window",
] }
