//! Domain-specific builder extension traits for LogUp bus interactions.
//!
//! Each trait encodes the tuple schema for one bus, providing typed
//! `send_*` / `receive_*` methods that replace manual `AirInteraction`
//! construction. Blanket impls on [`InteractionAirBuilder`] mean
//! [`DebugConstraintBuilder`] automatically supports all traits.
//!
//! Generated by [`define_bus!`] from schema declarations below.

use crate::air::interaction::core_buses;

// ── Access tuple types (shared by ReadAccess and WriteAccess buses) ──────

/// Runtime/witness-level access tuple value.
///
/// Canonical tuple order:
/// `(t, c, key[3], tx_index, val[W], is_null)`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AccessTupleValue<V> {
    /// Table identifier.
    pub table_id: u32,
    /// Column identifier.
    pub col_id: u16,
    /// Key limbs (`u64` decomposition).
    pub key_limbs: [u32; 3],
    /// Transaction index in batch.
    pub tx_index: u32,
    /// Encoded value limbs.
    pub value: Vec<V>,
    /// Null marker.
    pub is_null: bool,
}

/// AIR-level access tuple expression.
///
/// This remains separate from [`AccessTupleValue`] to avoid forcing one
/// generic type across runtime value and AIR expression domains.
#[derive(Clone, Debug)]
pub struct AccessTupleExpr<E> {
    /// Table identifier.
    pub table_id: E,
    /// Column identifier.
    pub col_id: E,
    /// Key limb 0.
    pub key_limb0: E,
    /// Key limb 1.
    pub key_limb1: E,
    /// Key limb 2.
    pub key_limb2: E,
    /// Transaction index in batch.
    pub tx_index: E,
    /// Encoded value limbs.
    pub value: Vec<E>,
    /// Null marker.
    pub is_null: E,
}

impl<E> AccessTupleExpr<E> {
    /// Convert to canonical tuple vector.
    pub fn into_values(self) -> Vec<E> {
        let mut values = Vec::with_capacity(self.value.len() + 7);
        values.push(self.table_id);
        values.push(self.col_id);
        values.push(self.key_limb0);
        values.push(self.key_limb1);
        values.push(self.key_limb2);
        values.push(self.tx_index);
        values.extend(self.value);
        values.push(self.is_null);
        values
    }
}

// ── Bus trait definitions via define_bus! macro ──────────────────────────

define_bus! {
    /// Extension trait for sending on the RangeCheck bus (C8).
    ///
    /// Tuple (1 element): `(value)` — single field element in `[0, 2^16)`.
    pub RangeCheckAirBuilder(
        core_buses::RANGE_CHECK,
        send_only send_range_check
    ) {
        val: expr,
    }
}

define_bus! {
    /// Extension trait for send/receive on the PoseidonPermutation bus (C5).
    ///
    /// Tuple (24 elements): `(input[16], output[8])`.
    pub PoseidonAirBuilder(
        core_buses::POSEIDON_PERM,
        send_poseidon_perm,
        receive_poseidon_perm
    ) {
        input: var_arr<16>,
        output: var_arr<8>,
    }

    /// Extension trait for send/receive on the CommitmentVerification bus (C6).
    ///
    /// Tuple (12 elements): `(t, c, comm_type, is_touched, digest[8])`.
    pub CommitmentAirBuilder(
        core_buses::COMMITMENT_VERIF,
        send_commitment,
        receive_commitment
    ) {
        t: expr,
        c: expr,
        comm_type: expr,
        is_touched: expr,
        digest: var_arr<8>,
    }

    /// Extension trait for send/receive on the ReadAccess bus (C10).
    ///
    /// Tuple (7+W elements): `(t, c, key[3], tx_index, val[W], is_null)`.
    pub ReadAccessAirBuilder(
        core_buses::READ_ACCESS,
        send_read_access,
        receive_read_access
    ) {
        tuple: access_tuple,
    }

    /// Extension trait for send/receive on the WriteAccess bus (C11).
    ///
    /// Tuple (7+W elements): `(t, c, key[3], tx_index, val[W], is_null)`.
    pub WriteAccessAirBuilder(
        core_buses::WRITE_ACCESS,
        send_write_access,
        receive_write_access
    ) {
        tuple: access_tuple,
    }

    /// Extension trait for send/receive on the EmptyColRead bus (C12).
    ///
    /// Tuple (2 elements): `(t, c)`.
    pub EmptyColReadAirBuilder(
        core_buses::EMPTY_COL_READ,
        send_empty_col_read,
        receive_empty_col_read
    ) {
        t: expr,
        c: expr,
    }

    /// Extension trait for send/receive on the BaseStateEntry bus (C13).
    ///
    /// Tuple (6+W elements): `(t, c, key[3], val[W], is_null)`.
    pub BaseStateEntryAirBuilder(
        core_buses::BASE_STATE_ENTRY,
        send_base_state_entry,
        receive_base_state_entry
    ) {
        t: expr,
        c: expr,
        key: u64limbs,
        val: var_slice,
        is_null: expr,
    }

    /// Extension trait for send/receive on the CoalescedWrite bus (C14).
    ///
    /// Tuple (6+W elements): `(t, c, key[3], val[W], is_null)`.
    pub CoalescedWriteAirBuilder(
        core_buses::COALESCED_WRITE,
        send_coalesced_write,
        receive_coalesced_write
    ) {
        t: expr,
        c: expr,
        key: u64limbs,
        val: var_slice,
        is_null: expr,
    }

    /// Extension trait for send/receive on the StaticTableLookup bus (C9).
    ///
    /// Tuple (5+W elements): `(t, c, key[3], val[W])`.
    pub StaticTableLookupAirBuilder(
        core_buses::STATIC_TABLE_LOOKUP,
        send_static_table_lookup,
        receive_static_table_lookup
    ) {
        t: expr,
        c: expr,
        key: u64limbs,
        value: var_slice,
    }

    /// Extension trait for send/receive on the SmtLeafDigest bus (C15).
    ///
    /// Tuple (18 elements): `(table_id, col_id, old_leaf[8], new_leaf[8])`.
    pub SmtLeafDigestAirBuilder(
        core_buses::SMT_LEAF_DIGEST,
        send_smt_leaf_digest,
        receive_smt_leaf_digest
    ) {
        table_id: expr,
        col_id: expr,
        old_leaf: var_arr<8>,
        new_leaf: var_arr<8>,
    }

    /// Extension trait for send/receive on the SmtTableRoot bus (C16).
    ///
    /// Tuple (17 elements): `(table_id, old_root[8], new_root[8])`.
    pub SmtTableRootAirBuilder(
        core_buses::SMT_TABLE_ROOT,
        send_smt_table_root,
        receive_smt_table_root
    ) {
        table_id: expr,
        old_root: var_arr<8>,
        new_root: var_arr<8>,
    }

    /// Extension trait for send/receive on the EmptyOldColumn bus (C19).
    ///
    /// Tuple (2 elements): `(t, c)`.
    pub EmptyOldColumnAirBuilder(
        core_buses::EMPTY_OLD_COLUMN,
        send_empty_old_column,
        receive_empty_old_column
    ) {
        t: expr,
        c: expr,
    }

    /// Extension trait for send/receive on the PropertyRead bus (C18).
    ///
    /// Tuple (4W+4 elements):
    /// `(t, c, query_type, query_arg0[W], query_arg1[W], result_val[W], result_key[W], is_null)`.
    #[allow(clippy::too_many_arguments)]
    pub PropertyReadAirBuilder(
        core_buses::PROPERTY_READ,
        send_property_read,
        receive_property_read
    ) {
        t: expr,
        c: expr,
        query_type: expr,
        query_arg0: var_slice,
        query_arg1: var_slice,
        result_val: var_slice,
        result_key: var_slice,
        is_null: expr,
    }

    /// Extension trait for send/receive on the SSMC old-entry anchor bus (C20).
    ///
    /// Tuple `(t, c, key[3], val[W], has_prev, prev_key[3], is_last_old, next_key[3])`.
    #[allow(clippy::too_many_arguments)]
    pub SsmcOldEntryAirBuilder(
        core_buses::SSMC_OLD_ENTRY,
        send_ssmc_old_entry,
        receive_ssmc_old_entry
    ) {
        t: expr,
        c: expr,
        key: u64limbs,
        val: var_slice,
        has_prev: expr,
        prev_key: u64limbs,
        is_last_old: expr,
        next_key: u64limbs,
    }
}
