[package]
name = "tabula-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
test-utils = ["blake3"]

[dependencies]
serde = { workspace = true }
borsh = { workspace = true }
thiserror = { workspace = true }
blake3 = { workspace = true, optional = true }

[dev-dependencies]
proptest = { workspace = true }
blake3 = { workspace = true }

[lints]
workspace = true
