[package]
name = "tabula-stark"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tabula-core = { workspace = true }
tabula-commitment = { workspace = true, features = ["stark"] }
thiserror = { workspace = true }
p3-field = { workspace = true }
p3-baby-bear = { workspace = true }
p3-air = { workspace = true }
p3-matrix = { workspace = true }
p3-uni-stark = { workspace = true }
rayon = { workspace = true }

[dev-dependencies]
tabula-core = { workspace = true }
p3-challenger = { workspace = true }

[lints]
workspace = true
