[package]
name = "tabula-testing"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
tabula-compiler = { workspace = true }
tabula-contract = { workspace = true }
tabula-core = { workspace = true, features = ["test-utils"] }
tabula-ir = { workspace = true }
tabula-profile = { workspace = true }
tabula-runtime = { workspace = true, features = ["prove"] }
tabula-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = "3"

[lints]
workspace = true
