[package]
name = "tabula-commitment"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
mock = ["blake3"]

[dependencies]
tabula-core = { workspace = true }
blake3 = { workspace = true, optional = true }
borsh = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
blake3 = { workspace = true }
